//  An invader is shown below
/*     
    ..........
    ....##....
    ...####...
    .##X##X##.
    .##X##X##.
    .########.
    .########.
    ..##..##..
    ..##..##..
    .##....##.
    ###....###
    ..........
*/
// Numeric declaration of this invader

#define IVDR RGBToWord(0xff,0xff,0x00)
const uint16_t InvaderImage[] = { \
    BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,\
    BGND,BGND,BGND,BGND,IVDR,IVDR,BGND,BGND,BGND,BGND,\
    BGND,BGND,BGND,IVDR,IVDR,IVDR,IVDR,BGND,BGND,BGND,\
    BGND,IVDR,IVDR,BGND,IVDR,IVDR,BGND,IVDR,IVDR,BGND,\
    BGND,IVDR,IVDR,BGND,IVDR,IVDR,BGND,IVDR,IVDR,BGND,\
    BGND,IVDR,IVDR,IVDR,IVDR,IVDR,IVDR,IVDR,IVDR,BGND,\
    BGND,IVDR,IVDR,IVDR,IVDR,IVDR,IVDR,IVDR,IVDR,BGND,\
    BGND,BGND,IVDR,IVDR,BGND,BGND,IVDR,IVDR,BGND,BGND,\
    BGND,BGND,IVDR,IVDR,BGND,BGND,IVDR,IVDR,BGND,BGND,\
    BGND,IVDR,IVDR,BGND,BGND,BGND,BGND,IVDR,IVDR,BGND,\
    IVDR,IVDR,IVDR,BGND,BGND,BGND,BGND,IVDR,IVDR,IVDR,\
    BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND \
    };   

/* 
 The player Defender Ship is as follows:
 ..........
 ....##....
 ....##....
 .########.
 ##########
 ##########
 */
// Numeric declaration of Defender
const uint16_t DefenderImage[] = { \
    BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,\
    BGND,BGND,BGND,BGND,WHI ,WHI ,BGND,BGND,BGND,BGND,\
    BGND,BGND,BGND,BGND,WHI ,WHI ,BGND,BGND,BGND,BGND,\
    BGND,WHI ,WHI ,WHI ,WHI ,WHI ,WHI ,WHI ,WHI ,BGND,\
    WHI ,WHI ,WHI ,WHI ,WHI ,WHI ,WHI ,WHI ,WHI ,WHI ,\
    WHI ,WHI ,WHI ,WHI ,WHI ,WHI ,WHI ,WHI ,WHI ,WHI ,\
};



/* The missile image is as follows 
    ..#..
    .###.
    .###.
    .###.
    .###.
    #####
    #####
    ..#..
*/

const uint16_t MissileImage[]= { \
    BGND,BGND,GRN ,BGND,BGND, \
    BGND,GRN ,GRN ,GRN ,BGND, \
    BGND,GRN ,GRN ,GRN ,BGND, \
    BGND,GRN ,GRN ,GRN ,BGND, \
    BGND,GRN ,GRN ,GRN ,BGND, \
    GRN ,GRN ,GRN ,GRN ,GRN , \
    GRN ,GRN ,GRN ,GRN ,GRN , \
    BGND,BGND,GRN ,BGND,BGND  \
};

// The explosion image is as follows
/*     
    ....##....
    #...##...#
    .#..##..#.
    ..#.##.#..
    ...####...
    ##########
    ##########
    ...####...
    ..#.##.#..
    .#..##..#.
    #...##...#
    ....##....
*/                    
// Numeric declaration of Explosion
#define EXPL RGBToWord(0xff,0x00,0x00)
const uint16_t ExplosionImage[] = { \
    BGND,BGND,BGND,BGND,EXPL,EXPL,BGND,BGND,BGND,BGND,\
    EXPL,BGND,BGND,BGND,EXPL,EXPL,BGND,BGND,BGND,EXPL,\
    BGND,EXPL,BGND,BGND,EXPL,EXPL,BGND,BGND,EXPL,BGND,\
    BGND,BGND,EXPL,BGND,EXPL,EXPL,BGND,EXPL,BGND,BGND,\
    BGND,BGND,BGND,EXPL,EXPL,EXPL,EXPL,BGND,BGND,BGND,\
    EXPL,EXPL,EXPL,EXPL,EXPL,EXPL,EXPL,EXPL,EXPL,EXPL,\
    EXPL,EXPL,EXPL,EXPL,EXPL,EXPL,EXPL,EXPL,EXPL,EXPL,\
    BGND,BGND,BGND,EXPL,EXPL,EXPL,EXPL,BGND,BGND,BGND,\
    BGND,BGND,EXPL,BGND,EXPL,EXPL,BGND,EXPL,BGND,BGND,\
    BGND,EXPL,BGND,BGND,EXPL,EXPL,BGND,BGND,EXPL,BGND,\
    EXPL,BGND,BGND,BGND,EXPL,EXPL,BGND,BGND,BGND,EXPL,\
    BGND,BGND,BGND,BGND,EXPL,EXPL,BGND,BGND,BGND,BGND,\
    };      
    
// Image definitions for brici

#define YLBK RGBToWord(255, 255, 48)

const uint16_t YELLBLK[] = { \
    BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,\
    BGND,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,BGND,\
    BGND,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,BGND,\
    BGND,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,BGND,\
    BGND,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,BGND,\
    BGND,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,BGND,\
    BGND,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,BGND,\
    BGND,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,BGND,\
    BGND,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,YLBK,BGND,\
    BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND \
};

#define GNBK RGBToWord(47, 249, 24)
const uint16_t GRENBLK[] = { \
    BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,\
    BGND,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,BGND,\
    BGND,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,BGND,\
    BGND,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,BGND,\
    BGND,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,BGND,\
    BGND,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,BGND,\
    BGND,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,BGND,\
    BGND,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,BGND,\
    BGND,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,GNBK,BGND,\
    BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND \
};

#define BLBK RGBToWord(24, 201, 249)
const uint16_t BLUEBLK[] = { \
    BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,\
    BGND,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BGND,\
    BGND,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BGND,\
    BGND,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BGND,\
    BGND,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BGND,\
    BGND,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BGND,\
    BGND,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BGND,\
    BGND,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BGND,\
    BGND,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BLBK,BGND,\
    BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND \
};

const uint16_t BAT[] = { \
    WHI, WHI ,WHI ,WHI ,WHI ,WHI ,WHI ,WHI ,WHI ,WHI , WHI, WHI ,WHI ,WHI ,WHI ,WHI ,WHI ,WHI ,WHI ,WHI ,\
    WHI ,WHI ,WHI ,WHI ,WHI ,WHI ,WHI ,WHI ,WHI ,WHI , WHI, WHI ,WHI ,WHI ,WHI ,WHI ,WHI ,WHI ,WHI ,WHI ,\
    WHI ,WHI ,WHI ,WHI ,WHI ,WHI ,WHI ,WHI ,WHI ,WHI , WHI, WHI ,WHI ,WHI ,WHI ,WHI ,WHI ,WHI ,WHI ,WHI  \
};
const uint16_t BALL[] = { \
    WHI, WHI ,
    WHI ,WHI 
};
